language: bash

env:
    global:
        - HUGO_VERSION=0.82.1

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

script:
    - ./hugo

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: public
    target_branch: master
    repo: YNUCPC/ynucpc.github.io
    on:
        branch: master
