baseURL = "https://ynucpc.github.io/"
languageCode = "ja-JP"
title = "YNU.cpc -横浜国立大学競技プログラミング部-"
theme = "universal"
defaultContentLanguage = "ja"
hasCJKLanguage = true

paginate = 10
pygmentsStyle = "friendly"
pygmentsCodeFences = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "author"

[menu]

# Main menu

[[menu.main]]
    weight = 1
    name = "Home"
    url = "/"

[[menu.main]]
    weight = 2
    name = "About"
    url = "/about/"

[[menu.main]]
    weight = 3
    name = "Blog"
    url = "/blog/"

[[menu.main]]
    identifier = "contest"
    weight = 4
    name = "Contests"
    # url = "/contests/"

[[menu.main]]
    parent = "contest"
    weight = 1
    name = "2019年度"
    url = "/contests/2019/"

[[menu.main]]
    parent = "contest"
    weight = 1
    name = "2020年度"
    url = "/contests/2020/"

[[menu.main]]
    parent = "contest"
    weight = 1
    name = "2021年度"
    url = "/contests/2021/"

[[menu.main]]
    parent = "contest"
    weight = 2
    name = "年度一覧"
    url = "/contests/"

[[menu.main]]
    weight = 5
    name = "Contact"
    url = "/contact/"

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Twitter"
    url = "https://twitter.com/ynu_cpc?lang=ja"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "YNU.cpc"
    defaultKeywords = ["YNU", "CPC", "競プロ", "競技プログラミング", "サークル", "横浜国立大学"]
    defaultDescription = "横浜国立大学競技プログラミング部"
    description = "横浜国立大学競技プログラミング部"
    images = ["img/banners/logo.png"]

    # Google Maps API key
    #googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "turquoise"

    # Contact form setting
    email = "ynu.cpc@gmail.com"

    about_us = """競技プログラミングに取り組む横浜国立大学の公認サークルです。
    詳しくは<a href="/about/">こちら</a>
    """
    copyright = "Copyright (c) 2018-2021, YNU.cpc; all rights reserved."

    # Format dates with Go's formatting
    date_format = "2006-01-02"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    #address = ""
    #latitude = ""
    #longitude = ""

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on ynu.cpc@gmail.com.</p>
      <p class="hidden-md hidden-lg">
      <a href="/contact/" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable or disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.features]
    enable = false

[params.testimonials]
    enable = false

[params.see_more]
    enable = false

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "最新の投稿"
    subtitle = "ブログの最新の投稿です。"

# Enable inline HTML in Markdown files
[markup.goldmark.renderer]
unsafe = true